
name: project_pyreact

services:


  nginx:
    image: nginxinc/nginx-unprivileged:alpine3.23-perl
    restart: unless-stopped

    read_only: true

    security_opt:
      - no-new-privileges

    cap_drop:
      - ALL

    tmpfs:
      - /tmp/:uid=101,gid=101,mode=1770,size=512m
      - /var/run/:uid=101,gid=101,mode=1770,size=512m
      - /var/cache/nginx/:uid=101,gid=101,mode=1770,size=512m

    ports:
      - "80:8080"
      - "443:8443"

    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 20s
      start_interval: 5s

    depends_on:
      postgresql:
        condition: service_healthy

    cpus: 0.5

    mem_limit: 2g

    pids_limit: 2048

    ulimits:
      nofile:
        soft: 65536
        hard: 65536

    networks:
      - frontend
      - backend


  redis:
    image: redis:trixie
    restart: unless-stopped

    networks:
      - frontend


  postgresql:
    image: postgres:18.4
    restart: unless-stopped

    user: "999:999"

    security_opt: 
      - no-new-privileges

    cap_drop:
      - ALL

    tmpfs:
      - /tmp/

    expose:
      - "5432"
    
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
    volumes:
      - ./postgres/data:/var/lib/postgresql
      - ./postgres/init-db/:/docker-entrypoint-initdb.d/
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
      start_interval: 10s

    cpus: 2

    mem_limit: 4g

    pids_limit: 2048

    shm_size: 1g

    ulimits:
      nofile:
        soft: 65336
        hard: 65536

    networks:
      - backend


  backend:
    build: ./backend

    container_name: backend
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #  interval: 1m
    #  timeout: 0s
    #  retries: 3
    #  start_period: 0s
    #  start_interval: 5s
      

    depends_on:
      postgresql:
        condition: service_healthy
    
    networks:
      - backend


  portainer:
    image: portainer/portainer
    restart: unless-stopped

    ports:
      - "9443:9443"
      - "9000:9000"
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  frontend:

  backend:
    internal: true
