name: project_pyreact

services:

  redis:
    image: redis:trixie

    networks:
      - frontend

  postgresql:
    image: postgres:18.4

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - ./postgres/data:/var/lib/postgresql
      - ./postgres/init-db/:/docker-entrypoint-initdb.d/

    ports:
      - "5432:5432"

    networks:
      - frontend

networks:
  frontend:


