
name: project_pyreact

services:

  nginx:
    image: nginx:stable-alpine3.23-perl
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html

    networks:
      - frontend

  redis:
    image: redis:trixie
    networks:
      - frontend

  postgresql:
    image: postgres:18.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql
      - ./postgres/init-db/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - frontend

  backend:
    build: ./backend
    container_name: pyreact-backend
    restart: unless-stopped
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    networks:
      - frontend

  portainer:
    image: portainer/portainer
    ports:
      - "9443:9443"
      - "9000:9000"
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  frontend:
